name: mcp_server
description: Dart plugin for implementing Model Context Protocol (MCP) servers. Provides tools to build MCP servers that can expose data, functionality, and interaction patterns to LLM applications.
version: 0.1.4
homepage: https://github.com/app-appplayer/mcp_server
repository: https://github.com/app-appplayer/mcp_server
issue_tracker: https://github.com/app-appplayer/mcp_server/issues

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  http: ^1.1.0
  json_annotation: ^4.9.0
  uuid: ^4.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
